### ISSUE TITLE
启动报错 java.lang.NoClassDefFoundError: java/sql/Time

### ISSUE THREAD

**Issue by saltfish13** [Kloping/Mirai_Plugins_Auto_Reply#16]
net.mamoe:mirai-console" v2.11.0-RC2
net.mamoe:mirai-console-terminal" v2.11.0-RC2
net.mamoe:mirai-core-all v2.11.0-RC2
Autoreply 0.5
![3D~(9 @KE (Y}Y9GJ5TCUMH](https://user-images.githubusercontent.com/59356579/168545588-cca1534c-0aa2-4265-915d-b335c4c419bb.png)

**Comment by Kloping** [comment]
应该是jdk的问题

**Comment by saltfish13** [comment]
我更换了mirai console用的jre 从17到18 jdk18都换了一遍，还是出现这个报错哎

**Comment by Kloping** [comment]
换低版本 16 11

**Comment by saltfish13** [comment]
2022-05-16 22:05:58 E/Custom Reply: java.lang.NoClassDefFoundError: java/sql/Time
java.lang.NoClassDefFoundError: java/sql/Time
        at AutoReply-v0.5.jar//com.alibaba.fastjson.util.TypeUtils.addBaseClassMappings(TypeUtils.java:1628)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.util.TypeUtils.<clinit>(TypeUtils.java:121)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.parser.ParserConfig.<init>(ParserConfig.java:202)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.parser.ParserConfig.<init>(ParserConfig.java:370)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.parser.ParserConfig.<init>(ParserConfig.java:366)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.parser.ParserConfig.<clinit>(ParserConfig.java:172)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.JSON.parseObject(JSON.java:298)
        at AutoReply-v0.5.jar//com.alibaba.fastjson.JSON.parseObject(JSON.java:588)
        at AutoReply-v0.5.jar//io.github.kloping.initialize.FileInitializeValue.toValue(FileInitializeValue.java:131)
        at AutoReply-v0.5.jar//io.github.kloping.initialize.FileInitializeValue.getValue(FileInitializeValue.java:58)
        at AutoReply-v0.5.jar//com.github.kloping.Conf.getInstance(Conf.java:37)
        at AutoReply-v0.5.jar//com.github.kloping.Resource.<clinit>(Resource.java:31)
        at AutoReply-v0.5.jar//com.github.kloping.Plugin0AutoReply.onEnable(Plugin0AutoReply.java:37)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:119)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:262)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:34)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:183)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:231)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ClassNotFoundException: java/sql/Time
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:306)
        ... 51 more

**Comment by Kloping** [comment]
是 jdk 的问题 java.sql 是java 内置的

**Comment by saltfish13** [comment]
我又更换了JDK11还是一样的问题，好像是我昨天在系统里安装了JDK18之后就出问题了

**Comment by Kloping** [comment]
你可以改 mcl.cmd 的内容 指定一下java

**Comment by saltfish13** [comment]
摁我现在修改的就是用mcl脚本下载的那个portable的JDK11，不过还是报同样的错误，有点神秘

**Comment by Kloping** [comment]
你用着个试试呢 
https://adoptopenjdk.net/archive.html

**Comment by saltfish13** [comment]
still,用的这个镜像的11lts

**Comment by Kloping** [comment]
你用linux or win

**Comment by saltfish13** [comment]
是windwos系统的机器，之前都是能正常启动的

**Comment by Kloping** [comment]
你的mcl.cmd 是这样嘛

@echo off

set JAVA_BINARY=你的jdk目录\bin\java.exe

%JAVA_BINARY% -Dfile.encoding=UTF-8 -jar ./mcl.jar

pause


示例

@echo off

set JAVA_BINARY=E:\development_environment\jdk-16.0.1\bin\java.exe

%JAVA_BINARY% -Dfile.encoding=UTF-8 -jar ./mcl.jar

pause

**Comment by saltfish13** [comment]
@echo off
set JAVA_BINARY="D:\Mirai_bot\java\bin\java.exe"
%JAVA_BINARY% -jar mcl.jar %*

只有这三行呢，没指定编码的那个

**Comment by Kloping** [comment]
你这个 D:\Mirai_bot\java\bin\java.exe  是你刚才下的 jdk 吗

**Comment by saltfish13** [comment]
对的，我直接给换进去了

**Comment by Kloping** [comment]
@echo off

set JAVA_BINARY=D:\Mirai_bot\java\bin\java.exe

%JAVA_BINARY% -version

pause

%JAVA_BINARY% -Dfile.encoding=UTF-8 -jar ./mcl.jar

pause


你复制我这个 运行下 看 日志

**Comment by saltfish13** [comment]
![image](https://user-images.githubusercontent.com/59356579/168620254-c0605bb6-2e6f-40ea-8f8d-8a2c060675da.png)

**Comment by Kloping** [comment]
再往下就报错了吗

**Comment by saltfish13** [comment]
到加载autoreply就报错了，信息与上面一致

**Comment by saltfish13** [comment]
![image](https://user-images.githubusercontent.com/59356579/168620698-4cf6572f-788c-4490-a7cf-589566b9b221.png)

**Comment by Kloping** [comment]
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
  23:22:09 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  23:22:09 [INFO] https://github.com/iTXTech/mirai-console-loader
  23:22:09 [INFO] This program is licensed under GNU AGPL v3
  23:22:10 [INFO] Fetching Mirai Console Loader Announcement...
  23:22:10 [INFO] Mirai Console Loader Announcement:
[WARNING] 您目前使用的仓库源 gitee 将不再受到支持
[WARNING] 我们已经停止对 gitee 源的同步更新
[WARNING] 如果您依然使用此源, 则不会再受到我们的更新推送
[WARNING]
[WARNING] 详见
[WARNING] `- https://mirai.mamoe.net/topic/1084/
[WARNING] `- https://github.com/project-mirai/mirai-repo-mirror
[WARNING]
[WARNING]                 Mamoe Technologies & iTX Technologies
[WARNING]                                            03/30/2022


  23:22:10 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  23:22:10 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0-M1
  23:22:11 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0-M1
  23:22:11 [INFO] Verifying "net.mamoe:mirai-core-all" v2.11.0-M1
  23:22:11 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
2022-05-16 23:22:11 I/main: Starting mirai-console...
2022-05-16 23:22:13 I/main: Backend: version 2.11.0-M1, built on 2022-03-08 20:34:54.
2022-05-16 23:22:13 I/main: Frontend Terminal: version 2.11.0-M1, provided by Mamoe Technologies
2022-05-16 23:22:13 I/main: Welcome to visit https://mirai.mamoe.net/
2022-05-16 23:22:13 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-05-16 23:22:13 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-05-16 23:22:13 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-05-16 23:22:13 I/plugin: Successfully loaded plugin Custom Reply v0.5
2022-05-16 23:22:13 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-05-16 23:22:13 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-05-16 23:22:13 I/plugin: Successfully loaded plugin io.github.Kloping.mirai.p1.CallApiPlugin v1.1
2022-05-16 23:22:13 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-05-16 23:22:13 I/Custom Reply: HRS-AutoReply-Plugin-loaded
2022-05-16 23:22:13 I/stdout: [github.kloping.ST][Info]  [05/16-23:22:13:616]=>WebExtension extension load
2022-05-16 23:22:13 I/stdout: [github.kloping.ST][Info]  [05/16-23:22:13:636]=>start sptool success
2022-05-16 23:22:13 I/Custom Reply: AutoReply 服务启动成功 address: http://localhost:20044?key=123456
2022-05-16 23:22:13 I/stdout: [github.kloping.ST][Debug] [05/16-23:22:13:639]=>计时任务结束...
2022-05-16 23:22:13 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-05-16 23:22:13 I/main: 4 plugin(s) enabled.
2022-05-16 23:22:13 I/main: mirai-console started successfully.
2022-05-16 23:22:14 W/stderr: 5月 16, 2022 11:22:14 下午 org.apache.coyote.AbstractProtocol init
2022-05-16 23:22:14 W/stderr: 信息: Initializing ProtocolHandler ["http-nio-20044"]
2022-05-16 23:22:14 W/stderr:
2022-05-16 23:22:14 W/stderr: 5月 16, 2022 11:22:14 下午 org.apache.catalina.core.StandardService startInternal
2022-05-16 23:22:14 W/stderr: 信息: Starting service [tomcat-default]
2022-05-16 23:22:14 W/stderr:
2022-05-16 23:22:14 W/stderr: 5月 16, 2022 11:22:14 下午 org.apache.catalina.core.StandardEngine startInternal
2022-05-16 23:22:14 W/stderr: 信息: Starting Servlet engine: [Apache Tomcat/9.0.55]
2022-05-16 23:22:14 W/stderr:
2022-05-16 23:22:14 W/stderr: 5月 16, 2022 11:22:14 下午 org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
2022-05-16 23:22:14 W/stderr: 警告: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [450] milliseconds.
2022-05-16 23:22:14 W/stderr:
2022-05-16 23:22:14 W/stderr: 5月 16, 2022 11:22:14 下午 org.apache.coyote.AbstractProtocol start
2022-05-16 23:22:14 W/stderr: 信息: Starting ProtocolHandler ["http-nio-20044"]
2022-05-16 23:22:14 W/stderr:
>

**Comment by Kloping** [comment]
不是很理解
我的一点问题都没有

**Comment by Kloping** [comment]
是 mcl 版本问题吗

**Comment by saltfish13** [comment]
今天更新MCL之后恢复正常了
