### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by EscapeA** [Kloping/Mirai_Plugins_Auto_Reply#20]
2022-08-10 23:27:51 E/Custom Reply java.lang.NoClassDefFoundError: io/github/kloping/initialize/FileInitializeValue
java.lang.NoClassDefFoundError: io/github/kloping/initialize/FileInitializeValue
	at com.github.kloping.Conf.getInstance(Conf.java:40)
	at com.github.kloping.Resource.<clinit>(Resource.java:31)
	at com.github.kloping.Plugin0AutoReply.onEnable(Plugin0AutoReply.java:37)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:158)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:214)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:277)
	at com.youngerhousea.mirai.compose.EntryPointKt$startApplication$1$1$1$1.invokeSuspend(EntryPoint.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.github.kloping.initialize.FileInitializeValue
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more

**Comment by RepentStar** [comment]
同样的问题，解决了踢我一下

**Comment by Kloping** [comment]
https://github.com/Kloping/Mirai_Plugins_Auto_Reply#%E4%BD%BF%E7%94%A8%E5%89%8D%E8%AF%B7%E6%A3%80%E6%9F%A5%E4%BE%9D%E8%B5%96lib-tts%E6%98%AF%E5%90%A6%E4%B8%80%E5%90%8C%E6%B7%BB%E5%8A%A0%E8%87%B3plugins-%E5%89%8D%E5%BE%80-releases-%E6%9F%A5%E6%89%BE

https://github.com/Kloping/Mirai_Plugins_Auto_Reply/releases/tag/lib-tts.1

**Comment by Kloping** [comment]
https://github.com/Kloping/Mirai_Plugins_Auto_Reply/releases
